service: test-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

  deploymentBucket: 
    name: test-lambda-function-1

  stage: dev
  region: ap-southeast-1

  iam:
      role:
        statements:
          - Effect: Allow
            Resource: '*'
            Action:
              - lambda:InvokeFunctionUrl
            # Resource: arn:aws:lambda:ap-southeast-1:193980408680:function:moli-customer-dev-customer

  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    # TEST_BUCKET: akmal-test-1

functions:
  lambdaCallApi:
    handler: index.lambdaCallApi
    timeout: 900
    memorySize: 1028

plugins:
 - serverless-offline